CREATE TABLE IF NOT EXISTS CLEANING_DATA (
    cleaning_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    location VARCHAR(255),
    duration BIGINT,
    area_cleaned DOUBLE,
    water_usage DOUBLE,
    power_usage DOUBLE
);
